name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0 9 6 *'
    - cron: '6 6 9 6 *'
    - cron: '29 12 9 6 *'
    - cron: '8 19 9 6 *'
    - cron: '55 0 10 6 *'
    - cron: '53 4 10 6 *'
    - cron: '45 7 10 6 *'
    - cron: '49 10 10 6 *'
    - cron: '3 13 10 6 *'
    - cron: '29 15 10 6 *'
    - cron: '37 19 10 6 *'
    - cron: '31 21 10 6 *'
    - cron: '47 0 11 6 *'
    - cron: '15 4 11 6 *'
    - cron: '36 9 11 6 *'
    - cron: '8 13 11 6 *'
    - cron: '54 16 11 6 *'
    - cron: '20 0 12 6 *'
    - cron: '26 3 12 6 *'
    - cron: '27 4 12 6 *'
    - cron: '45 7 12 6 *'
    - cron: '19 9 12 6 *'
    - cron: '34 11 12 6 *'
    - cron: '44 12 12 6 *'
    - cron: '45 15 12 6 *'
    - cron: '39 17 12 6 *'
    - cron: '8 0 13 6 *'
    - cron: '47 5 13 6 *'
    - cron: '26 8 13 6 *'
    - cron: '58 12 13 6 *'
    - cron: '3 17 13 6 *'
    - cron: '26 21 13 6 *'
    - cron: '49 1 14 6 *'
    - cron: '2 2 14 6 *'
    - cron: '4 4 14 6 *'
    - cron: '26 7 14 6 *'
    - cron: '56 9 14 6 *'
    - cron: '57 11 14 6 *'
    - cron: '40 13 14 6 *'
    - cron: '46 15 14 6 *'
    - cron: '29 16 14 6 *'
    - cron: '49 19 14 6 *'
    - cron: '45 0 15 6 *'
    - cron: '48 3 15 6 *'
    - cron: '44 6 15 6 *'
    - cron: '8 10 15 6 *'
    - cron: '40 13 15 6 *'
    - cron: '52 15 15 6 *'
    - cron: '49 18 15 6 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Harsh Vekariya"
          git config --global user.email "harshvekariya203@gmail.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push